---
title: "Lab 4: Pokemon"
author: "Luisa Simpao"
date: "February 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data set

```{r}
library(tidyverse)
library(dplyr)

pokes <- read.csv("https://www.dropbox.com/s/i0lwxgv86eaoq4o/pokemon.csv?dl=1")
```

# 1. At least one plot, with proper labels.

```{r}

# get to know data
summary(pokes)

# analysis starts here
pokes <- pokes %>% 
  mutate(
    Catch_Difficulty = case_when(
      Catch_Rate > 170 ~ "Easy",
      between(Catch_Rate, 85, 170) ~ "Medium", 
      Catch_Rate < 85 ~ "Hard"
    ),
    Catch_Difficulty = factor(Catch_Difficulty, levels = c("Easy", "Medium", "Hard"))
  ) 

pokes %>% count(Catch_Difficulty)

pokes %>% 
  group_by(Type_1) %>% 
  summarize(avg_Total = mean(Total)) %>% 
  mutate(
    Type_1 = fct_reorder(Type_1, avg_Total)
  ) %>%
  ggplot(aes(x = Type_1, y = avg_Total, fill = Type_1)) +
  geom_col()
  
pokes %>% 
  group_by(Catch_Difficulty, Type_1) %>% 
  summarize(avg_Total = mean(Total)) %>% 
  mutate(
    Type_1 = fct_reorder(Type_1, avg_Total)
  ) %>%
  ggplot(aes(x = Type_1, y = avg_Total, fill = Type_1)) +
  geom_col() +
  facet_wrap(~Catch_Difficulty)

pokes %>% 
  ggplot(aes(x = Catch_Rate, y = Total, color = Catch_Difficulty)) + 
  geom_point()

```

# 2. At least one statistical analysis or model.
```{r}
  
# chi-square test
pk_type <- pokes %>%
  count(Type_1, Catch_Difficulty) %>%
  spread(key = Catch_Difficulty, value = n) %>%
  filter(Easy >= 3, Medium >=3, Hard >= 3)
pk_type %>% 
  select(-Type_1) %>% 
  chisq.test()

# t-tests
em <- pokes %>%
  count(Type_1, Catch_Difficulty) %>% 
  filter(Catch_Difficulty == "Easy" | Catch_Difficulty == "Medium")
t.test(n ~ Catch_Difficulty, data = em)

eh <- pokes %>%
  count(Type_1, Catch_Difficulty) %>% 
  filter(Catch_Difficulty == "Easy" | Catch_Difficulty == "Hard")
t.test(n ~ Catch_Difficulty, data = eh)

mh <- pokes %>%
  count(Type_1, Catch_Difficulty) %>% 
  filter(Catch_Difficulty == "Medium" | Catch_Difficulty == "Hard")
t.test(n ~ Catch_Difficulty, data = mh)

```

# 3. Proper discussion and interpretation of all work.

Conclusion: 